Workaround region weirdness with availablity zones
Try Tutorial vpc: https://goo.gl/iSCsBd

Terraform s3 backend doesn't support us-west-2, but us-west-1 is ok

Workaround region weirdness with availablity zones

Error: Error applying plan:

3 error(s) occurred:

 * aws_subnet.private_1_subnet: 1 error(s) occurred:

 * aws_subnet.private_1_subnet: Error creating subnet:
   InvalidParameterValue: Value (us-west-2a) for parameter
   availabilityZone is invalid. Subnets can currently only be created in
   the following availability zones: us-west-1b, us-west-1c.
         status code: 400, request id: d79d861c-fc2e-4cd0-b732-59a390860e86
 * aws_subnet.public_subnet: 1 error(s) occurred:

 * aws_subnet.public_subnet: Error creating subnet:
   InvalidParameterValue: Value (us-west-2a) for parameter
   availabilityZone is invalid. Subnets can currently only be created in
   the following availability zones: us-west-1b, us-west-1c.
         status code: 400, request id: 8b325f65-b047-4c9e-a55b-a1b65296642d

 * aws_subnet.private_2_subnet: 1 error(s) occurred:

 * aws_subnet.private_2_subnet: Error creating subnet:
   InvalidParameterValue: Value (us-west-2b) for parameter
   availabilityZone is invalid. Subnets can currently only be created in
   the following availability zones: us-west-1c, us-west-1b.
         status code: 400, request id: d0624629-8d96-4bce-9c21-be478043143e

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with any
resources that successfully completed. Please address the error above
and apply again to incrementally change your infrastructure.